-- Enable UUID extension (optional but good practice)
create extension if not exists "uuid-ossp";

-- 1. Users Table
create table public.users (
  username text primary key,
  email text unique not null,
  password text not null,
  avatar text, -- Stores base64 string (consider using Storage buckets for large images later)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Events Table
create table public.events (
  id text primary key,
  name text not null,
  currency text default 'USD',
  access_code text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Event Members (Many-to-Many)
create table public.event_members (
  event_id text references public.events(id) on delete cascade,
  username text references public.users(username) on delete cascade,
  role text default 'member',
  primary key (event_id, username)
);

-- 4. Expenses Table
create table public.expenses (
  id bigint generated by default as identity primary key,
  event_id text references public.events(id) on delete cascade not null,
  title text not null,
  amount double precision not null,
  original_amount double precision,
  original_currency text,
  exchange_rate double precision,
  payer text not null,
  category text,
  date text not null,
  settled boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Expense Participants (Many-to-Many)
create table public.expense_participants (
  expense_id bigint references public.expenses(id) on delete cascade,
  username text, -- Intentionally not a foreign key to allow keeping history if user deleted? Or enforce FK? Let's enforce FK for consistency.
  -- username text references public.users(username) on delete cascade, 
  -- Actually, keeping it loose for now to match app logic which might have legacy users
  primary key (expense_id, username)
);

-- 6. Settlements Table
create table public.settlements (
  id bigint generated by default as identity primary key,
  event_id text references public.events(id) on delete cascade not null,
  payer text not null,
  recipient text not null,
  amount double precision not null,
  payment_currency text,
  converted_amount double precision,
  exchange_rate double precision,
  date text not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security (RLS)
-- For this simple app, we will disable RLS to allow the service role (your app) full access.
-- In a real production app with frontend-direct access, you'd enable this.
alter table public.users enable row level security;
alter table public.events enable row level security;
alter table public.event_members enable row level security;
alter table public.expenses enable row level security;
alter table public.expense_participants enable row level security;
alter table public.settlements enable row level security;

-- Create policies that allow full access for now (since we use the API key server-side)
-- OR just disable RLS if using the service_role key. 
-- For simplicity with the 'anon' key in Streamlit, we need policies.

create policy "Enable all access for all users" on public.users for all using (true) with check (true);
create policy "Enable all access for all users" on public.events for all using (true) with check (true);
create policy "Enable all access for all users" on public.event_members for all using (true) with check (true);
create policy "Enable all access for all users" on public.expenses for all using (true) with check (true);
create policy "Enable all access for all users" on public.expense_participants for all using (true) with check (true);
create policy "Enable all access for all users" on public.settlements for all using (true) with check (true);
